require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PartnerWebsitesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PartnerWebsite. As you add validations to PartnerWebsite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartnerWebsitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all partner_websites as @partner_websites" do
      partner_website = PartnerWebsite.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:partner_websites)).to eq([partner_website])
    end
  end

  describe "GET #show" do
    it "assigns the requested partner_website as @partner_website" do
      partner_website = PartnerWebsite.create! valid_attributes
      get :show, {:id => partner_website.to_param}, valid_session
      expect(assigns(:partner_website)).to eq(partner_website)
    end
  end

  describe "GET #new" do
    it "assigns a new partner_website as @partner_website" do
      get :new, {}, valid_session
      expect(assigns(:partner_website)).to be_a_new(PartnerWebsite)
    end
  end

  describe "GET #edit" do
    it "assigns the requested partner_website as @partner_website" do
      partner_website = PartnerWebsite.create! valid_attributes
      get :edit, {:id => partner_website.to_param}, valid_session
      expect(assigns(:partner_website)).to eq(partner_website)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PartnerWebsite" do
        expect {
          post :create, {:partner_website => valid_attributes}, valid_session
        }.to change(PartnerWebsite, :count).by(1)
      end

      it "assigns a newly created partner_website as @partner_website" do
        post :create, {:partner_website => valid_attributes}, valid_session
        expect(assigns(:partner_website)).to be_a(PartnerWebsite)
        expect(assigns(:partner_website)).to be_persisted
      end

      it "redirects to the created partner_website" do
        post :create, {:partner_website => valid_attributes}, valid_session
        expect(response).to redirect_to(PartnerWebsite.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved partner_website as @partner_website" do
        post :create, {:partner_website => invalid_attributes}, valid_session
        expect(assigns(:partner_website)).to be_a_new(PartnerWebsite)
      end

      it "re-renders the 'new' template" do
        post :create, {:partner_website => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested partner_website" do
        partner_website = PartnerWebsite.create! valid_attributes
        put :update, {:id => partner_website.to_param, :partner_website => new_attributes}, valid_session
        partner_website.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested partner_website as @partner_website" do
        partner_website = PartnerWebsite.create! valid_attributes
        put :update, {:id => partner_website.to_param, :partner_website => valid_attributes}, valid_session
        expect(assigns(:partner_website)).to eq(partner_website)
      end

      it "redirects to the partner_website" do
        partner_website = PartnerWebsite.create! valid_attributes
        put :update, {:id => partner_website.to_param, :partner_website => valid_attributes}, valid_session
        expect(response).to redirect_to(partner_website)
      end
    end

    context "with invalid params" do
      it "assigns the partner_website as @partner_website" do
        partner_website = PartnerWebsite.create! valid_attributes
        put :update, {:id => partner_website.to_param, :partner_website => invalid_attributes}, valid_session
        expect(assigns(:partner_website)).to eq(partner_website)
      end

      it "re-renders the 'edit' template" do
        partner_website = PartnerWebsite.create! valid_attributes
        put :update, {:id => partner_website.to_param, :partner_website => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested partner_website" do
      partner_website = PartnerWebsite.create! valid_attributes
      expect {
        delete :destroy, {:id => partner_website.to_param}, valid_session
      }.to change(PartnerWebsite, :count).by(-1)
    end

    it "redirects to the partner_websites list" do
      partner_website = PartnerWebsite.create! valid_attributes
      delete :destroy, {:id => partner_website.to_param}, valid_session
      expect(response).to redirect_to(partner_websites_url)
    end
  end

end
